name: macOS build and test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
         persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.24'

      - name: Build macOS binaries (CGO required for sandbox)
        run: |
          make out/macos-amd64/crc-admin-helper out/macos-arm64/crc-admin-helper

      - name: Verify sandbox symbols
        run: |
          nm out/macos-arm64/crc-admin-helper | grep sandbox_init
          nm out/macos-amd64/crc-admin-helper | grep sandbox_init

      - name: Tests
        run: make test

      - name: Lint
        run: make lint

      - name: Verify sandbox
        run: make sandbox-test

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: crc-admin-helper macOS executables
          path: |
            out/macos-amd64/crc-admin-helper
            out/macos-arm64/crc-admin-helper
